global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'skydive-forecast-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
        labels:
          service: 'gateway'

  - job_name: 'skydive-forecast-user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
        labels:
          service: 'user-service'

  - job_name: 'skydive-forecast-analysis-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analysis-service:8082']
        labels:
          service: 'analysis-service'

  - job_name: 'skydive-forecast-location-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['location-service:8083']
        labels:
          service: 'location-service'
